### ISSUE TITLE
Slow after some time

### ISSUE THREAD

**Issue by joery1337** [JaraLowell/OgarServ#137]
Hey,

After a while when there's been like 8000 players, the server gets really laggy.

Is there a way to solve it, or is it node.js?

Thanks.

**Comment by JaraLowell** [comment]
Is why we auto restart the servers after like 24 or 48 hours; However, a lot of Linux version out there have a serious issue with how memory is cleaned or the likes, for some reason for example my Ubuntu likes to create a cache bigger then the amount of memory i have over time. So that can cause a heap of lag to if you have no real memory left to actually use. In End however, node also is a limit, we trying at OgarServ to be as lo as possibly in CPU and memory consumption, but in end Node is a bit memory leaking no matter how  perfect the JS is you create.

**Comment by joery1337** [comment]
Would using an other Linux distro like Fedora or CentOS improve it?

In less then 8 hours it's already really laggy for me.

You did a great job on the memory consumption!

**Comment by JaraLowell** [comment]
Aslo check what version of node you are using. 

As of like V8 version 3.17.13.0 the option to set max new space bin removed. So when you start the server with the --max-new-space-size=xxxx option the server wont start trowing an error.

We do suggest that you use node v0.10.25 ~ v0.10.43 (V8 version 3.14.5.9) as these versions use the lowest memory with OgarServ.

To change your node version:
sudo npm cache clean -f --force
sudo npm install -g n
sudo n 0.10.43

After this, make sure to install the node modules again by first removing the node_modules folder and dooing an npm install ws http fs sys mysql url underscore and then run the server with the command line:
node --nouse-idle-notification --expose-gc --always-compact --max-new-space-size=2048 --max-old-space-size=2048 index.js

**Comment by joery1337** [comment]
I was already using node version `v0.10.25`, wasn't runnig node with these arguments `-max-new-space-size=2048 --max-old-space-size=2048`.

I'll try and hope it's going to last longer!
