### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by mafiakb** [JaraLowell/OgarServ#152]
When is the next update?

**Comment by darknight99x** [comment]
lol rip responses

**Comment by JaraLowell** [comment]
Am sorta bussy real life, have a few small fixes to commit;

Personally i do not know if i want to add the multi protocol, or even add the new agar.io protocol; as i my self would never ever use it. So if i where to add it it would be modular so people can either choose what protocol to use so that we do not kill the server with an huge if statement code. However this still something i am thinking on. Not sure yet where i want to go; as current version is working stable and smooth with my client.

**Comment by mafiakb** [comment]
add in u client, graphic quality :) low very hard
