### ISSUE TITLE
How to control minion?

### ISSUE THREAD

**Issue by Niall7459** [JaraLowell/OgarServ#168]
I have ERTP enabled in config.
And client also supports ERTP controls.

But what does each key do I cant seem to notice.

Many thanks.

**Comment by JaraLowell** [comment]
i have not finished the minions yet right now, working on finishing the remote admin thingy first then will look at the minions. same as not all game modes yet work, will go trough them as things advance. till we have 1.7 finished and ready for release.

**Comment by Niall7459** [comment]
Ok, I love the remote admin by the way!

Also how does a suprise cell spawn?

**Comment by JaraLowell** [comment]
Right now they only active inside the Halloween and Christmas game mode, i guess i could move them to FFA and make it an config option to enable them or not 😈 the Remote admin client is almost done to a point that we can read what we want to read. Plus some extra visuals. Though most of it wont show to you yet because need the server update. I will push that out when i get the final part working. After that i go and look at minion. Biggest test was testing if the Remote Admin client could stay logged in 24 hour without killing FireFox 👿

**Comment by Niall7459** [comment]
Ok. A note about the Remote admin was I could not do "help" nothing would shoe just saying.

**Comment by JaraLowell** [comment]
Yah right now we not send the 'help' to the remote admin client. But that was because at start of project we had no scroll bar. As we have a working one now i guess i could switch that on to. 😈
