### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Edgeset** [JaraLowell/OgarServ#44]
Lag with 
8gb ram, 2xcore 2,4ghz
with only two servers:
1) connected players 114
players: 33
uses 150% of cpu
2) connected players 24
players: 16
how can fix it?
Can anyone help me found a dedicated/vps for 300/400 online players?

**Comment by JaraLowell** [comment]
With an average of 10KB/s per active player watching... and thus 138 users connected means 1.38MB/s. Knowing most VPS have shared and capped bandwidth yah you gone get there soon and fast. Obviously so to 138 open connections eats a lot of CPU power, and with only 33 playing you maybe better of with like max 50 servers times 3. Though you still gone get to the bandwidth cap fast, specially as most VPS servers have an additional cap of x-per month. So that us some thing to look in to when hosting a game server that has many people connecting.
