### ISSUE TITLE
Is this possible?

### ISSUE THREAD

**Issue by Ciao121** [JaraLowell/OgarServ#54]
I was thinking if serverVersion could be set on client connection instead of at congif level.
In example:
- an user connects with a *_new *_client, the server detects it and sets, for this client, serverVersion = 1
- an user connects with a *_old *_ client, the server detects it and sets, for this client, serverVersion = 0

The server keep track of all those client version and react for each one sending out packets needed for that specific client. In this way it should be possible to have, on the same server, old and new clients at the same time (regardless of what this implies legally).
Is it, in theory, possible? Can the client version be detected in any way?

**Comment by JaraLowell** [comment]
Server it self supports 3 clients versions at 1 go; however, it the client that has the issue. It will understand only 1 type from server or you add in to the server to like fix it to read all 3 protocols as well (though only need understand 2)

**Comment by Ciao121** [comment]
Maybe I do not fully understand your anserwer.
Can the client version be detected from the server on client's connect?

**Comment by JaraLowell** [comment]
Technically yes, but why would you want to. You have your site, or use use Agar.io and that is what should work. Switching back and forth is just bad. I would more say, why are there still old clients out there while being new is just a change if like 8 lines of js code. It be a whole lot more lines in server just to fix an lazy admins client :angry: as eventually support for old, gone be bye bye. Depending what agar.io all might change in the future.

**Comment by Ciao121** [comment]
The reason: I have a server creation service (agarserv.com). For example I could make an api, usable by webmasters, to create a server via api call. I would like this server to be usable by my own users (using the official client) but also from creator's site users. And 99% of those site's uses old protocol clients.

**Comment by JaraLowell** [comment]
To be fair, you only have to edit your client to accept both old and new server. As it is the client that is being difficult. I Would as i do, run in a mode compatible with agar.io, and try to force private site owners to start fixing there clients to also support this. As really it is only like... 

## function updateNodes

OLD Client
`posX = view.getInt16(offset, true);
 offset += 2;
 posY = view.getInt16(offset, true);
 offset += 2;`
New Client v561.20 and up
`posX = view.getInt32(offset, true);
 offset += 4;
 posY = view.getInt32(offset, true);
 offset += 4;`

## function sendMouseMove

OLD Client
`msg = prepareData(21);
 msg.setUint8(0, 16);
 msg.setFloat64(1, X, true);
 msg.setFloat64(9, Y, true);
 msg.setUint32(17, 0, true);`
New Client  v561.20 and up
`msg = prepareData(9);
 msg.setUint8(0, 16);
 msg.setFloat64(1, X, true);
 msg.setFloat64(3, Y, true);
 msg.setUint32(5, 0, true);`

And thats the only 2 differences between new and old. Eventually, any server out there will stop support for older clients. So i would say, webmaster, fix your scripts.

**Comment by Ciao121** [comment]
I totally agree with you. Webmaster should update their clients :)
Really thank you for your time!!!

**Comment by Ciao121** [comment]
I tried your client side solution but it didn't work for me. Anyway I know this is not the place to talk about clients so it's not a problem. Anyway I confirm I totally agree with your POV.

**Comment by makandz** [comment]
@JaraLowell I think you forgot to close this ^_^

**Comment by EnTerr** [comment]
Server auto-detecting client version is actually a **great idea** because of seeing how many OgarServ servers are misconfigured for "legacy" mode instead of "normal" one. I think this is because of the bad choice of words calling them "private" vs "Agar.io" - people think by choosing Agar.io they'd be selling their soul to Miniclip! If i were installing a _private_ server (which Ogar is), i would have chosen "_private_" because that's what i wanted. I wouldn't have a clue that instead it means a 11-month old, ancient protocol from the times Agar.io was not bought out by a company.

In any event, a reality check today: look at http://ogar.mivabe.nl/master - ~**50% of servers are running in legacy mode**, and wrongly so! So apparently these people are not updating their client as shown above and not switching their servers to what has been "normal" for almost a year! I surmise they must be running legacy clients because of thinking "that's what _private_ requires". 

Here is another thing: if server auto-adapts, it will be able to **accept both legacy and normal clients at the same time**! Ain't that great?

How can it be done? Let's say OgarServ assumes `serverVersion` from `gameserver.ini` in a connection from a new client until it sees a "mouse" packet (set direction, ID=16). At this point it can look at the size of the packet received and figure out which dialect the client actually speaks, so continue speaking that version for that client from there on.

**Comment by Andrews54757** [comment]
its easy, i could add it

**Comment by Andrews54757** [comment]
just put some code that only works on the newer client and put a try/catch block on it. if it returns an error, use the old client protocals

**Comment by EnTerr** [comment]
@Andrews54757 not easy at all on the client side! See the differences described above, relevant one is server is sending Update (server type 16) packet with different x,y field sizes (int16 vs int32). Note since there are multiple blobs per packet, packet size is not indicator. And list is zero terminated. Going the wrong way as a client, you may trip - OR you may misinterpret the meaning wrong with not exceptions. It's very unclean.

On the other hand, OgarServ has a very clean way to detect the client type from the Mouse packet (client type 16) size. Again, there is no excuse for clients still running July 2015 version of the protocol - but even less excuse for mis-configured servers forcing July 2015 version onto non-JS clients (like me). See #142 if you want to know more on my situation

**Comment by Andrews54757** [comment]
im talking about changing the server protocals. not changeing the client

**Comment by EnTerr** [comment]
@Andrews54757 - Try-catch is quick and dirty, may - or _may not_ work. I already described above how that can be done cleanly in the server - by relying on the check that already exists in client_#16 packet: https://github.com/JaraLowell/OgarServ/blob/master/src/PacketHandler.js#L61

I am not planning to run my own servers, rather i hope to persuade the project owner to make the change.

**Comment by Andrews54757** [comment]
whatever, i dont care. im gonna stick to ogar unlimited and make it there instead as some people use old clients and some people use the newer one

**Comment by EnTerr** [comment]
Attitude, @Andrews54757 :-)

Does your Ogar Unlimited even need to worry about zombie clients from before July 2015? From what i can see, this is "feature" only of OgarServ - seems nobody else has this issue? Not Ogar - and i presume not OgUn? 

Note it is a good thing if you need not worry about this! OgarServ however has the misfortune ~50% of all servers being mis-configured in "legacy" mode (i figure because of bad choice of words "private" vs "agar.io" in documentation)

PS. correction - i saw legacy is handled in OgUn by `gameServer.config.packetversion=1`

**Comment by JaraLowell** [comment]
Problem is, even though we can also obviously change the coordinates server side to int16 or int32 based on mouse imput; it meas it will send the 1st wave on info in the mode default to server. If this be wrong, your client usually hangs before the server can switch. Is why it was not done automatically but by settings. 

Reason why it was called Agar.io mode vs Private; that the 'legacy' mode all should be using is used by agar.io, well was up till a week ago. So now i would guess mode be called Int32 vs Int16 i guess... and next mode after figuring out new protocol be Int8 even though that would be wrong as it simplu puts two int valls together or you can not get the correct map size with single int8 value.

**Comment by EnTerr** [comment]
@JaraLowell - sure, but let's say my client survives the first wave under the "wrong" protocol. Besides, i was thinking if there was such feature server-side, i can force my client to send as very 1st packet be a mouse one (16) and that would "correct" the server.

This issue stems from Agar protocol not having proper handshake in the first place, like on connect saying "i am this version and will speak this dialect, k 10x" - or having some negotiation like in VNC

**Comment by JaraLowell** [comment]
As we receive the mouse info it be pretty easy to set a flag in the server for that player what protocol is used. Just need check if on sending this flag is accessible and correct for the user we send the info back to. Something we might soon to need for the new protocol agar.io uses. That be if they even wish servers to be created for there service. Right now they do not seem to interested in that and can change it again like every week...

**Comment by EnTerr** [comment]
Right. Umm, since `gameServer.config.serverVersion` flag is global per server - instead it has to be  per-player (or per-websocket connection if you will, same thing) thing

**Comment by JaraLowell** [comment]
Remember though config wise; int32 allows for a much larger world map then int16, and maybe even less with current new version.

**Comment by EnTerr** [comment]
@JaraLowell - sorry, what do you mean? The "new" protocol (> v561.20, post July 2015) uses int32 **both** for mouse coords and blob x,y.

**Comment by Mistik** [comment]
> The reason: I have a server creation service (agarserv.com). For example I could make an api, usable by webmasters, to create a server via api call. I would like this server to be usable by my own users (using the official client) but also from creator's site users. And 99% of those site's uses old protocol clients.

hey AgarServ isnt working anymore

**Comment by Mistik** [comment]
@[Ciao121](https://github.com/Ciao121)
